/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class StrawModelTest {
    @Test public void testAppHasAGreeting() {
        StrawModel classUnderTest = new StrawModel();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
